repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
    - id: seed-isort-config
      language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
      additional_dependencies: ["toml"]
      language_version: python3.7
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.3
    hooks:
    - id: flake8
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-json
    -   id: sort-simple-yaml
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
