[tool.poetry]
name = "aiocrontab"
version = "0.1.0"
description = "Crontab implementation in asyncio "
authors = ["Bhavesh Praveen <bhavespraveen.dev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
croniter = "^0.3.31"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-mock = "^3.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
